# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 6e5edd7c7f37ad77d413eab7c663894476f88f5458558a9556597e17dde333361bf171f0822e4d0f11bb3470880f08120eaab4f821a5e101f03586fd6e509f1e

test:
  domain_name: example.com 
  secret_key_base: 15f945e89ab051c7281f92acd28b02052dd42deabbf1280d78b4eaf3026c4f440a705c1c5e5cf09f896c80fd13677b8a4a56f5eb344a5382f3d44f5047c30dd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
